In [2]:
#Importamos las librerias que vamos a utilizar
#Panda es una libreria de python que nos permite hacer data frames
import pandas as pd
#Numpy es para operaciones de matrices
import numpy as np
#Seaborn es para graficar y hacer comparativos
import seaborn as sns

#Graficas de forma general
#import matplotlib as plt
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
ls

57654-0.txt                   postgresql-practice-master (1).zip
archive.zip                   Práctica clases 18 de enero - Netflix.ipynb
city_temperature.csv          simple.json
data_by_artist.csv            spotify_dataset.zip
data_by_genres.csv            Temperaturas.ipynb
data_by_year.csv              Untitled10.ipynb
data.csv                      Untitled1.ipynb
Data from html.ipynb          Untitled2.ipynb
Data from HTML.ipynb          Untitled3.ipynb
data_w_genres.csv             Untitled4.ipynb
ETL completo .ipynb           Untitled5.ipynb
Examen del 2 parcial.ipynb    Untitled6.ipynb
Examen segundo parcial.ipynb  Untitled7.ipynb
Explorando datos.ipynb        Untitled8.ipynb
Libros.ipynb                  Untitled9.ipynb
lost+found/                   Untitled.ipynb
Pandas.ipynb                  vino_data.zip
Pokemon.csv                   vinos_datas.zip

In [4]:
#Extraemos los datos de la librería
!unzip vino_data.zip

Archive:  vino_data.zip
  inflating: winemag-data-130k-v2.csv
  inflating: winemag-data-130k-v2.json
  inflating: winemag-data_first150k.csv

In [5]:
ls

57654-0.txt                                  simple.json
archive.zip                                  spotify_dataset.zip
city_temperature.csv                         Temperaturas.ipynb
data_by_artist.csv                           Untitled10.ipynb
data_by_genres.csv                           Untitled11.ipynb
data_by_year.csv                             Untitled1.ipynb
data.csv                                     Untitled2.ipynb
Data from html.ipynb                         Untitled3.ipynb
Data from HTML.ipynb                         Untitled4.ipynb
data_w_genres.csv                            Untitled5.ipynb
ETL completo .ipynb                          Untitled6.ipynb
Examen del 2 parcial.ipynb                   Untitled7.ipynb
Examen segundo parcial.ipynb                 Untitled8.ipynb
Explorando datos.ipynb                       Untitled9.ipynb
Libros.ipynb                                 Untitled.ipynb
lost+found/                                  vino_data.zip
Pandas.ipynb                                 vinos_datas.zip
Pokemon.csv                                  winemag-data-130k-v2.csv
postgresql-practice-master (1).zip           winemag-data-130k-v2.json
Práctica clases 18 de enero - Netflix.ipynb  winemag-data_first150k.csv

In [6]:
#Creamos las variables para poder hacer dataframes con lo extraido anteriormente
df = pd.read_csv("winemag-data_first150k.csv", encoding='latin')

In [54]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum SelecciÃ³n Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen RodrÃ­guez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La BÃ©gude, named af...",La BrÃ»lade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la BÃ©gude

In [11]:
#1 ¿Cuáles son las 5 variedades de vino más abundantes y menos abundantes?
#Abundantes
sp = df.head(5).sort_values(by='variety', ascending=True)

In [12]:
sp

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La BÃ©gude, named af...",La BrÃ»lade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la BÃ©gude
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum SelecciÃ³n Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen RodrÃ­guez

In [22]:
#MENOS ABUNDANTES
sd = df.head(150929).sort_values(by='variety', ascending=False)

In [23]:
sd

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
5215,5215,Macedonia,This Macedonian white is bright yellow with gr...,NaN,86,13.0,Tikves,NaN,NaN,Å½ilavka,Stobi
5050,5050,Macedonia,This Macedonian wine made from 100% Å½ilavka h...,NaN,88,15.0,Tikves,NaN,NaN,Å½ilavka,Stobi
80433,80433,Austria,"Yes, cherry is a good name for the red cherry ...",Austrian Cherry,86,15.0,NiederÃ¶sterreich,NaN,NaN,Zweigelt,R&A; Pfaffl
85597,85597,Austria,This has rich fruits that are solid and firmly...,Matthias Peck,93,37.0,Burgenland,NaN,NaN,Zweigelt,Scheiblhofer
111264,111264,Austria,"This is in the fresh, fruity style of Zweigelt...",Blauer Zweigelt,85,16.0,Burgenland,NaN,NaN,Zweigelt,Nittnaus Anita und Hans
...,...,...,...,...,...,...,...,...,...,...,...
56230,56230,Greece,"Sweet, jammy aromas and flavors of red berry, ...",NaN,82,15.0,Peloponnese,NaN,NaN,Agiorgitiko,Nasiakos
119287,119287,Greece,"This plucky red starts with aromas of tobacco,...",NaN,84,12.0,Nemea,NaN,NaN,Agiorgitiko,Kouros
35480,35480,Greece,"Cigarbox, mint, balsamic and leather lead this...",NaN,85,17.0,Nemea,NaN,NaN,Agiorgitiko,Boutari
113780,113780,Greece,"A simple, Beaujolais-like nose of purple fruit...",Agiorgitiko,84,20.0,Nemea,NaN,NaN,Agiorgitiko,Boutari
107905,107905,Greece,This single-vineyard Agiorgitiko has an earthy...,Old Vines Single Vineyard,88,26.0,Nemea,NaN,NaN,Agiorgitiko,Papaioannou

In [25]:
dr = pd.read_csv("winemag-data-130k-v2.csv", encoding='latin')

In [56]:
dr.head

<bound method NDFrame.head of         Unnamed: 0   country  \
0                0     Italy
1                1  Portugal
2                2        US
3                3        US
4                4        US
...            ...       ...
129966      129966   Germany
129967      129967        US
129968      129968    France
129969      129969    France
129970      129970    France

                                              description  \
0       Aromas include tropical fruit, broom, brimston...
1       This is ripe and fruity, a wine that is smooth...
2       Tart and snappy, the flavors of lime flesh and...
3       Pineapple rind, lemon pith and orange blossom ...
4       Much like the regular bottling from 2012, this...
...                                                   ...
129966  Notes of honeysuckle and cantaloupe sweeten th...
129967  Citation is given as much as a decade of bottl...
129968  Well-drained gravel soil gives this wine its c...
129969  A dry style of Pinot Gris, this is crisp with ...
129970  Big, rich and off-dry, this is powered by inte...

                                    designation  points  price  \
0                                 VulkÃ  Bianco      87    NaN
1                                      Avidagos      87   15.0
2                                           NaN      87   14.0
3                          Reserve Late Harvest      87   13.0
4            Vintner's Reserve Wild Child Block      87   65.0
...                                         ...     ...    ...
129966  Brauneberger Juffer-Sonnenuhr SpÃ¤tlese      90   28.0
129967                                      NaN      90   75.0
129968                                    Kritt      90   30.0
129969                                      NaN      90   32.0
129970           Lieu-dit Harth CuvÃ©e Caroline      90   21.0

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN
1                   Douro                  NaN                NaN
2                  Oregon    Willamette Valley  Willamette Valley
3                Michigan  Lake Michigan Shore                NaN
4                  Oregon    Willamette Valley  Willamette Valley
...                   ...                  ...                ...
129966              Mosel                  NaN                NaN
129967             Oregon               Oregon       Oregon Other
129968             Alsace               Alsace                NaN
129969             Alsace               Alsace                NaN
129970             Alsace               Alsace                NaN

               taster_name taster_twitter_handle  \
0          Kerin OâKeefe          @kerinokeefe
1               Roger Voss            @vossroger
2             Paul Gregutt          @paulgwineÂ
3       Alexander Peartree                   NaN
4             Paul Gregutt          @paulgwineÂ
...                    ...                   ...
129966  Anna Lee C. Iijima                   NaN
129967        Paul Gregutt          @paulgwineÂ
129968          Roger Voss            @vossroger
129969          Roger Voss            @vossroger
129970          Roger Voss            @vossroger

                                                    title          variety  \
0                      Nicosia 2013 VulkÃ  Bianco  (Etna)      White Blend
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)   Portuguese Red
2           Rainstorm 2013 Pinot Gris (Willamette Valley)       Pinot Gris
3       St. Julian 2013 Reserve Late Harvest Riesling ...         Riesling
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...       Pinot Noir
...                                                   ...              ...
129966  Dr. H. Thanisch (Erben MÃ¼ller-Burggraef) 2013...         Riesling
129967                  Citation 2004 Pinot Noir (Oregon)       Pinot Noir
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  GewÃ¼rztraminer
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)       Pinot Gris
129970  Domaine Schoffit 2012 Lieu-dit Harth CuvÃ©e Ca...  GewÃ¼rztraminer

                                           winery
0                                         Nicosia
1                             Quinta dos Avidagos
2                                       Rainstorm
3                                      St. Julian
4                                    Sweet Cheeks
...                                           ...
129966  Dr. H. Thanisch (Erben MÃ¼ller-Burggraef)
129967                                   Citation
129968                            Domaine Gresser
129969                       Domaine Marcel Deiss
129970                           Domaine Schoffit

[129971 rows x 14 columns]>

In [43]:
#De acuerdo a su nacionalidad ¿Cuál es el vino más lejano a Mérida
sd = df.head().sort_values(by='country', ascending=True)

In [44]:
sd

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
4,4,France,"This is the top wine from La BÃ©gude, named af...",La BrÃ»lade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la BÃ©gude
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum SelecciÃ³n Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen RodrÃ­guez
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi

In [47]:
#Indique si existe alguna relación lineal entre los puntos del vino y su precio
relation = df[['price','points']]

In [46]:
relation

        price  points
0       235.0      96
1       110.0      96
2        90.0      96
3        65.0      96
4        66.0      95
...       ...     ...
150925   20.0      91
150926   27.0      91
150927   20.0      91
150928   52.0      90
150929   15.0      90

[150930 rows x 2 columns]

In [48]:
#4 ¿Cuál es el valor promedio del precio de los vinos?
df.describe()

          Unnamed: 0         points          price
count  150930.000000  150930.000000  137235.000000
mean    75464.500000      87.888418      33.131482
std     43569.882402       3.222392      36.322536
min         0.000000      80.000000       4.000000
25%     37732.250000      86.000000      16.000000
50%     75464.500000      88.000000      24.000000
75%    113196.750000      90.000000      40.000000
max    150929.000000     100.000000    2300.000000

In [62]:
#El catador voss roger tiene el 20% de los vinos ¿Cuántos vinos son?
dr.taster_name.value_counts()

Roger Voss            25514
Michael Schachner     15134
Kerin OâKeefe       10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne KrebiehlÂ MW      3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: taster_name, dtype: int64

In [67]:
dr.taster_name.value_counts(Roger Voss *.20)

SyntaxError: invalid syntax (<ipython-input-67-f4daeef2a419>, line 1)